-- Build device scripts from src/ into scripts/.
--
-- The E16 has no module system: a scene loads exactly one .lua file and there is nothing
-- on the device to require() a second file from. So sharing code means textual inlining,
-- done here rather than by hand.
--
-- A source file pulls in shared code with:
--
--     --!include lib/stepped.lua
--
-- paths relative to src/. Includes are emitted before the including file's own body, so
-- locals they define are in scope. `--@assign` directives are hoisted to the very top of
-- the output, since the App parses them there.
--
-- Run with: mise exec -- lua build.lua

local SRC = "src"
local OUT = "scripts"
-- 8000 bytes of uploaded size, per the Lua Scripting API Guide v1.2.0, which documents the
-- editor's counter as `uploaded-size / 8000`. This supersedes the manual's contradictory
-- 4000-byte figure. upload_size() below only strips comments, while the App also minifies
-- (renaming locals), so a script measuring slightly over here may still fit.
local LIMIT = 8000

local function read(path)
    local f = io.open(path, "r")
    if not f then return nil end
    local s = f:read("a")
    f:close()
    return s
end

local function lines_of(s)
    local out = {}
    for line in (s .. "\n"):gmatch("([^\n]*)\n") do out[#out + 1] = line end
    -- gmatch above adds one empty trailing element; drop it
    if out[#out] == "" then out[#out] = nil end
    return out
end

--- Split a source file into its assignment directives, its include paths, and the rest.
local function partition(src)
    local assigns, includes, body = {}, {}, {}
    for _, line in ipairs(lines_of(src)) do
        local inc = line:match("^%s*%-%-!include%s+(%S+)%s*$")
        if line:match("^%s*%-%-@assign") then
            assigns[#assigns + 1] = (line:gsub("^%s+", ""))
        elseif inc then
            includes[#includes + 1] = inc
        else
            body[#body + 1] = line
        end
    end
    return assigns, includes, body
end

--- Rough estimate of what the App will upload: comments and blank lines stripped.
local function upload_size(src)
    local n = 0
    for _, line in ipairs(lines_of(src)) do
        local trimmed = line:gsub("^%s+", ""):gsub("%s+$", "")
        if trimmed ~= "" and not trimmed:match("^%-%-") then
            n = n + #(trimmed:gsub("%s+", " ")) + 1
        end
    end
    return n
end

local function build(name)
    local src = assert(read(SRC .. "/" .. name), "cannot read " .. name)
    local assigns, includes, body = partition(src)

    local parts = {}
    parts[#parts + 1] = "-- GENERATED by build.lua from " .. SRC .. "/" .. name
    parts[#parts + 1] = "-- Edit that file, not this one."
    parts[#parts + 1] = ""

    if #assigns > 0 then
        for _, a in ipairs(assigns) do parts[#parts + 1] = a end
        parts[#parts + 1] = ""
    end

    for _, inc in ipairs(includes) do
        local lib = assert(read(SRC .. "/" .. inc), "cannot read include " .. inc)
        local lib_assigns, lib_includes, lib_body = partition(lib)
        assert(#lib_assigns == 0, inc .. " must not declare assignments")
        assert(#lib_includes == 0, "nested includes are not supported (" .. inc .. ")")
        parts[#parts + 1] = "-- ===== " .. inc .. " ====="
        for _, l in ipairs(lib_body) do parts[#parts + 1] = l end
        parts[#parts + 1] = ""
    end

    parts[#parts + 1] = "-- ===== " .. name .. " ====="
    for _, l in ipairs(body) do parts[#parts + 1] = l end

    local out = table.concat(parts, "\n"):gsub("\n\n\n+", "\n\n") .. "\n"

    local path = OUT .. "/" .. name
    local f = assert(io.open(path, "w"))
    f:write(out)
    f:close()

    local size = upload_size(out)
    local flag = size > LIMIT and "  OVER LIMIT" or ""
    print(string.format("%-24s %5d bytes (limit ~%d)%s", path, size, LIMIT, flag))
    return size <= LIMIT
end

-- Build every top-level .lua in src/ (lib/ is only ever inlined).
local ok = true
local pipe = io.popen("ls " .. SRC .. "/*.lua 2>/dev/null")
for path in pipe:lines() do
    local name = path:match("([^/]+)$")
    ok = build(name) and ok
end
pipe:close()

os.exit(ok and 0 or 1)
